name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Create RSA private key
        run: |
          mkdir -p src/main/resources/certs
          printf '%s\n' '${{ secrets.JWT_PRIVATE_KEY }}' > src/main/resources/certs/private.pem

      - name: Build and test
        run: ./mvnw clean verify

      - name: Check SonarCloud authentication
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -sS \
            -u "$SONAR_TOKEN:" \
            https://sonarcloud.io/api/authentication/validate


      - name: Check SonarCloud Quality Gate access
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -sS \
            -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=compliance-engine"


      - name: SonarCloud analysis
        run: ./mvnw sonar:sonar -Dsonar.token="${{ secrets.SONAR_TOKEN }}" -Dsonar.qualitygate.wait=true